"""
LaTeX research paper generator
Compiles agent discussions into a formatted research paper
"""

from typing import List, Dict
from datetime import datetime


class LatexPaperGenerator:
    """
    Generates LaTeX formatted research papers from agent discussions
    """
    
    def __init__(self):
        self.title = "Untitled Research Paper"
        self.authors = []
        self.abstract = ""
        self.sections = []
        self.references = []
        
    def set_metadata(self, title: str, authors: List[str], abstract: str):
        """Set paper metadata"""
        self.title = title
        self.authors = authors
        self.abstract = abstract
    
    def add_section(self, title: str, content: str, subsections: List[Dict] = None):
        """Add a section to the paper"""
        section = {
            "title": title,
            "content": content,
            "subsections": subsections or []
        }
        self.sections.append(section)
    
    def add_reference(self, reference: str):
        """Add a reference"""
        self.references.append(reference)
    
    def generate_latex(self) -> str:
        """Generate complete LaTeX document"""
        
        latex = r"""\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepackage{algorithm}
\usepackage{algorithmic}

\title{""" + self.title + r"""}
\author{""" + " \\and ".join(self.authors) + r"""}
\date{""" + datetime.now().strftime("%B %Y") + r"""}

\begin{document}

\maketitle

\begin{abstract}
""" + self.abstract + r"""
\end{abstract}

\section{Introduction}
This paper presents collaborative research conducted by multiple AI agents, 
each specializing in different aspects of artificial intelligence research.

"""
        
        # Add all sections
        for section in self.sections:
            latex += f"\n\\section{{{section['title']}}}\n"
            latex += section['content'] + "\n"
            
            # Add subsections if any
            for subsection in section.get('subsections', []):
                latex += f"\n\\subsection{{{subsection['title']}}}\n"
                latex += subsection['content'] + "\n"
        
        # Add example figure with TikZ
        latex += r"""

\section{Visualization}

\begin{figure}[h]
\centering
\begin{tikzpicture}
\begin{axis}[
    xlabel={Epoch},
    ylabel={Accuracy},
    width=10cm,
    height=6cm,
    grid=major,
    legend pos=south east
]
\addplot[color=blue,mark=*] coordinates {
    (1,0.65) (2,0.72) (3,0.78) (4,0.83) (5,0.87)
    (6,0.89) (7,0.91) (8,0.92) (9,0.93) (10,0.94)
};
\addlegendentry{Training Accuracy}

\addplot[color=red,mark=square] coordinates {
    (1,0.62) (2,0.68) (3,0.73) (4,0.77) (5,0.80)
    (6,0.82) (7,0.83) (8,0.84) (9,0.84) (10,0.85)
};
\addlegendentry{Validation Accuracy}
\end{axis}
\end{tikzpicture}
\caption{Example training curve showing model convergence}
\label{fig:training}
\end{figure}

"""
        
        # Add architecture diagram
        latex += r"""
\begin{figure}[h]
\centering
\begin{tikzpicture}[
    node distance=2cm,
    box/.style={rectangle, draw, minimum width=2cm, minimum height=1cm, align=center}
]
    \node[box] (input) {Input Layer};
    \node[box, right of=input] (hidden1) {Hidden\\Layer 1};
    \node[box, right of=hidden1] (hidden2) {Hidden\\Layer 2};
    \node[box, right of=hidden2] (output) {Output Layer};
    
    \draw[->] (input) -- (hidden1);
    \draw[->] (hidden1) -- (hidden2);
    \draw[->] (hidden2) -- (output);
\end{tikzpicture}
\caption{Neural network architecture diagram}
\label{fig:architecture}
\end{figure}

"""
        
        # Add references
        if self.references:
            latex += r"""
\section{References}
\begin{enumerate}
"""
            for ref in self.references:
                latex += f"\\item {ref}\n"
            
            latex += r"""\end{enumerate}
"""
        
        latex += r"""
\section{Conclusion}
This research paper was collaboratively generated by multiple specialized AI agents,
demonstrating the potential of multi-agent systems in automated research synthesis.

\end{document}
"""
        
        return latex
    
    def save_to_file(self, filename: str = "research_paper.tex"):
        """Save LaTeX to file"""
        latex_content = self.generate_latex()
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(latex_content)
        return filename
    
    def generate_simple_diagram(self, diagram_type: str) -> str:
        """Generate TikZ code for common diagram types"""
        
        diagrams = {
            "flowchart": r"""
\begin{tikzpicture}[node distance=2cm, auto]
    \node (start) [draw, rectangle] {Start};
    \node (process1) [draw, rectangle, below of=start] {Process Data};
    \node (decision) [draw, diamond, aspect=2, below of=process1] {Valid?};
    \node (process2) [draw, rectangle, below of=decision] {Execute};
    \node (end) [draw, rectangle, below of=process2] {End};
    
    \draw[->] (start) -- (process1);
    \draw[->] (process1) -- (decision);
    \draw[->] (decision) -- node {Yes} (process2);
    \draw[->] (decision) -| node {No} ++(3,0) |- (process1);
    \draw[->] (process2) -- (end);
\end{tikzpicture}
""",
            "attention": r"""
\begin{tikzpicture}
    \foreach \x in {1,2,3,4} {
        \node[draw, circle] at (\x,0) {Q\x};
        \node[draw, circle] at (\x,2) {K\x};
        \node[draw, circle] at (\x,4) {V\x};
    }
    \node at (2.5, -1) {Attention Mechanism};
\end{tikzpicture}
"""
        }
        
        return diagrams.get(diagram_type, "% Diagram not found")
